version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-auth-sample
    volumes:
      - ./postgres_data:/var/lib/postgresql/data