// Code generated by entc, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSigninWith holds the string denoting the signin_with field in the database.
	FieldSigninWith = "signin_with"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLoggedOutAt holds the string denoting the logged_out_at field in the database.
	FieldLoggedOutAt = "logged_out_at"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSigninWith,
	FieldEmail,
	FieldPassword,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLoggedOutAt,
	FieldUUID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultLoggedOutAt holds the default value on creation for the "logged_out_at" field.
	DefaultLoggedOutAt func() time.Time
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() uuid.UUID
)

// SigninWith defines the type for the "signin_with" enum field.
type SigninWith string

// SigninWith values.
const (
	SigninWithEmail   SigninWith = "email"
	SigninWithGoogle  SigninWith = "google"
	SigninWithTwitter SigninWith = "twitter"
)

func (sw SigninWith) String() string {
	return string(sw)
}

// SigninWithValidator is a validator for the "signin_with" field enum values. It is called by the builders before save.
func SigninWithValidator(sw SigninWith) error {
	switch sw {
	case SigninWithEmail, SigninWithGoogle, SigninWithTwitter:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for signin_with field: %q", sw)
	}
}
